## YAML Template.
---
server.port: 8888
security:
    username: ram
    password: nepal
    
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/student_db
        username: root
        password: mysql
spring.jpa.hibernate.ddl-auto: update
